### PR TITLE
feat: Added logo 96x96 and updated install.sql

### PR DESCRIPTION
**Pull request by 0x3r1k**
**Pull Request Description**

I changed the sql file since it was old and I made the logo 96x96 and png.

**Features**:
- feat: Changed the logo to 96x96 and the logo file to .png and updated install.sql

### CODE REVIEW

**Comment by BombayV** [comment]
Change version to 0.0.2 since it mostly fixing and updating rather than minor feature.

**Comment by 0x3r1k** [comment]
Ah, okay. I'll change it now

**Comment by 0x3r1k** [comment]
👍

**Comment by BombayV** [comment]
It should be 0.1.1

**Pull request merged**
